# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    msg = "custom message"
    upload_to_play_store()
    slack_message(content:msg)
  end

 lane :slack_message do | options |
    content = options[:content]
    slack(
        message: content,
        payload: {
            "Build Date" => Time.new.to_s,
            "Built by" => "Jenkins",
            "extra message"=> content,
        },
        default_payloads: [:git_branch]

      )
 end

  error do |lane, exception|
   slack(
        message: exception.message,
        success: false,
        payload: {
                    "Build Date" => Time.new.to_s,
                    "Built by" => "Jenkins",
                },
                default_payloads: [:git_branch]
      )
   end
 end